### ISSUE TITLE
members nav bar highlight not working

### ISSUE THREAD

**Issue by mrzl** [LacunaLab/LacunaLab.github.io#9]
@transfluxus -> 15e0eb89bdb64fc91e805c5a94a0169088d0130f

**Comment by mrzl** [comment]
when being scrolled to the members section, the where navbar entry is highlighted instead

**Comment by transfluxus** [comment]
I guess it depends on the screensize. 
Line 52 for in the index.html sets a magic number.

**Comment by mrzl** [comment]
bah.. you got any idea on how to fix that? cuz i dont. @hamoid, you?

**Comment by hamoid** [comment]
I don't know how it's currently implemented, but I would highlight the link by calculating which page position is closest to the y value found at 33% distance from the top border of the screen. I'll take a look.

**Comment by hamoid** [comment]
Now I see the code in index.html. Shouldn't we move it to js/ ? Also, all the hard coded values won't work for different screen sizes. I think we should calculate those based on the current screen height. 

Where does this code come from? Was it written by us? or copied from somewhere?

Also, should we delete js/*scroll* since it seems to be part of the latest jQuery?

**Comment by transfluxus** [comment]
Ya, that can go into a js when it's done. Makes it easier to find for others in the beginning I thought.
I wrote that.
true- I thought the scroll js files are gone already. gonna remove them in the next commit

**Comment by hamoid** [comment]
We can take a look at mellisonic.com There it works, also when you scroll up and down. Even if the sections are different heights.

**Comment by transfluxus** [comment]
but that's a different behavior. I should check the design again, or talk with aurelia about when to change the mark. yours selects one when it reaches the top. I thought it changes when it comes in from the bottom, or something in the middle.
I just changed it, see how this is

**Comment by hiroMTB** [comment]
Looks like it works ok now on my env. I will close and pls reopen if somebody fond it doesn't.
